config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'lists#index'

  # get "/lists/new" => "lists#new", as: :make_a_list
  # get "/lists/:id" => "lists#show", as: :list
  # post "/lists" => "lists#create"
  # get "/lists" => "lists#index"
  # delete "/lists/:id" => "lists#destroy"

  resources :lists, except: [:edit, :update] do
    resources :items, shallow: true
  end

  get "/sandbox/twitter" => "sandbox#twitter"
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user_1, class_name: "User"
  belongs_to :user_2, class_name: "User"
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :list
  validates_presence_of :list, :description
  validates_length_of :description, minimum: 2
  validates_uniqueness_of :description, scope: :list
  validate :due_date_cannot_be_in_the_past

  private

  def due_date_cannot_be_in_the_past
    if due_date.present? && due_date < Date.today
      errors.add :due_date, "can't be in the past"
    end
  end
end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user
  has_many :items, dependent: :destroy

  validates_presence_of :user, :title
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :lists
  has_many :items, through: :lists

  def friends
    ids  = Friendship.where(user_1: self).pluck :user_2_id
    ids += Friendship.where(user_2: self).pluck :user_1_id
    User.where(id: ids.uniq)
  end

  def floopy?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  include Pundit
  after_action :verify_authorized, unless: :devise_controller?

  rescue_from Pundit::NotAuthorizedError do |e|
    flash[:danger] = "NO!"
    redirect_to "/"
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_list, only: [:new, :create]

  def new
    @item = @list.items.new
    authorize @item
  end

  def create
    @item = @list.items.new approved_params
    authorize @item
    if @item.save
      flash[:notice] = "Item created!"
      redirect_to @list
    else
      render :new
    end
  end

  def edit
    @item = Item.find params[:id]
    authorize @item
  end

  def update
    @item = Item.find params[:id]
    authorize @item
    if @item.update approved_params
      flash[:notice] = "Item updated!"
      redirect_to @item.list
    else
      render :edit
    end
  end

  private

  def set_list
    @list = List.find params[:list_id]
  end

  def approved_params
    params.require(:item).permit(:description, :due_date)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  skip_after_action :verify_authorized, only: [:index]

  def new
  end

  def create
    list = current_user.lists.new title: params[:title]
    authorize list
    list.save!
    redirect_to "/lists"
  end

  def index
    @lists = current_user.lists
  end

  def show
    @list = List.find params[:id]
    authorize @list
  end

  def destroy
    list = List.find params[:id]
    authorize list
    list.destroy
    redirect_to "/lists"
  end
end

app/controllers/sandbox_controller.rb
class SandboxController < ApplicationController
  skip_before_action :authenticate_user!
  skip_after_action :verify_authorized
  
  def twitter
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @username = "World"
  end

  def super_secret
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sandbox_helper.rb
module SandboxHelper
end

app/views/items/_form.html.erb
<%= bootstrap_form_for [@list, @item] do |f| %>
  <%= f.text_field :description %>
  <%= f.date_field :due_date %>
  <button class="btn btn-primary">Save</button>
<% end %>

app/views/items/edit.html.erb
<h1>Edit Item</h1>

<%= render partial: "form" %>

app/views/items/new.html.erb
<h1>Add a New Item</h1>

<%= render partial: "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "RailsTodos" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">RailsTodos</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Lists", "/lists" %></li>
            <li><%= link_to "New List", "/lists/new" %></li>
          </ul>
          <ul class="nav navbar-nav pull-right">
            <% if user_signed_in? %>
              <li><%= link_to "Account", edit_user_registration_path %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <% if Rails.env.development? %>
          <p><%= params[:controller] %>#<%= params[:action] %></p>
        <% end %>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/lists/index.html.erb
<h2>Your Lists</h2>
<!-- <a href="/lists/new">Add a List</a> -->
<!-- <%= link_to "Add a List", "/lists/new" %> -->
<%= link_to "Add a List", new_list_path %>

<ul>
  <% @lists.each do |list| %>
    <li>
      <%= link_to list.title, list %>
      <!-- <form method="POST" action="/lists/<%= list.id %>">
        <input name="_method" type="hidden" value="DELETE">
        need CSRF token -->

      <!-- Take 1: writing a form directly -->
      <!-- <%= form_tag "/lists/#{list.id}", method: :delete do %>
        <button>X</button>
      <% end %> -->

      <!-- <%= button_to "X", "/lists/#{list.id}", method: :delete %> -->

      <%= link_to "X", list, method: :delete %>
    </li>
  <% end %>
</ul>

app/views/lists/new.html.erb
<!-- <form method="POST" action="/lists"> -->
<%= form_tag "/lists" do %>
  <input type="text" placeholder="Title" name="title">
  <button>Save</button>
<% end %>
<!-- </form> -->

app/views/lists/show.html.erb
<%= link_to "Show all", "/lists", class: "btn btn-default" %>
<% if policy(@list).add_items? %>
  <%= link_to "New item", new_list_item_path(@list), class: "btn btn-default" %>
<% end %>

<h2>
  <%= @list.title %>
  <span class="badge"><%= @list.items.count %></span>
</h2>

<table class="table table-hover table-striped table-condensed">
  <thead>
    <tr>
      <th></th>
      <th>Description</th>
      <th>Due</th>
      <th>Buttons</th>
    </tr>
  </thead>
  <tbody>
    <% @list.items.each do |item| %>
      <tr>
        <td>
          <span class="test" foo="bar" data-foo="<%= item.id %>">
            <%= item.id %>
          </span>
        </td>
        <td><%= item.description %></td>
        <td><%= item.due_date %></td>
        <td>
          <% if policy(item).edit? %>
            <%= link_to "Edit", edit_item_path(item), class: "btn btn-default btn-xs" %>
          <% end %>

          <a href="#" class="btn btn-default btn-xs js-btn" data-item-id="<%= item.id %>">
            Edit with Javascript
          </a>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/sandbox/twitter.html.erb
<div id="new-tweet">
  <textarea class="form-control" id="tweet-contents"></textarea>

  <button class="btn btn-primary" id="save-tweet">Save</button>

  <p></p>

  <ul class="item-list"></ul>

</div>

<div id="new-counter">

<p>0</p>
<button class="btn btn-primary" id="add-counter">+</button>
<button class="btn btn-primary" id="sub-counter">-</button>
<button class="btn btn-primary" id="reset-counter">Reset</button>
<ul class="counter-list"></ul>
<button class="btn btn-primary" id="clear-list">Clear List</button>
</div>

app/views/welcome/index.html.erb
<h1>Welcome, <%= @username %>!</h1>